CREATE TABLE INVENTORY_INFO_ALL 
(
  ID VARCHAR2(32 BYTE) DEFAULT sys_guid() NOT NULL 
, FACE_VALUE NUMBER 
, GAME_CODE NUMBER 
, GAME_NAME VARCHAR2(32 BYTE) 
, II_JIANGZU NUMBER 
, II_CASE NUMBER 
, II_PACKAGE NUMBER 
, II_MONEY NUMBER 
, INBOUND_JIANGZU NUMBER 
, INBOUND_CASE NUMBER 
, INBOUND_PACKAGE NUMBER 
, INBOUND_MONEY NUMBER 
, OUTBOUND_JIANGZU NUMBER 
, OUTBOUND_CASE NUMBER 
, OUTBOUND_PACKAGE NUMBER 
, OUTBOUND_MONEY NUMBER 
, EI_JIANGZU NUMBER 
, EI_CASE NUMBER 
, EI_PACKAGE NUMBER 
, EI_MONEY NUMBER 
, MANAGE_DATE VARCHAR2(10 BYTE) 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX TABLE1_PK ON INVENTORY_INFO_ALL (ID ASC) 
      LOGGING 
      TABLESPACE SPORTS_LOTTERY_DATA 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SPORTS_LOTTERY_DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;
