CREATE TABLE SALES_ALL 
(
  ID VARCHAR2(32 BYTE) DEFAULT sys_guid() NOT NULL 
, CITY_CODE VARCHAR2(4 BYTE) 
, CITY_NAME VARCHAR2(20 BYTE) 
, CONFIRM_PACKAGE NUMBER 
, CONFIRM_MONEY NUMBER 
, CONFIRM_PROPORTION VARCHAR2(8 BYTE) 
, ACTIVE_PACKAGE NUMBER 
, ACTIVE_MONEY NUMBER 
, ACTIVE_PROPORTION VARCHAR2(8 BYTE) 
, DUIJIANG_NUMBER NUMBER 
, DUIJIANG_MONEY NUMBER 
, DUIJIANG_PROPORTION VARCHAR2(8 BYTE) 
, MANAGE_DATE VARCHAR2(10 BYTE) 
, CONSTRAINT SALES_ALL_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SALES_ALL_PK ON SALES_ALL (ID ASC) 
      LOGGING 
      TABLESPACE SPORTS_LOTTERY_DATA 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SPORTS_LOTTERY_DATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;
